### ISSUE TITLE
Build fail on master due to protobuf experimental 

### ISSUE THREAD

**Issue by norandom** [zinclabs/zincobserve#763]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

The current master branch causes build fails for me. Details below.

```
marius@shell:~/Media/Source/zincobserve$ git rev-parse HEAD
6326acb4ed7d709e43d80d4921e49c33f1e73d1e
```

Build command:

```
marius@shell:~/Media/Source/zincobserve$ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)


cargo +nightly build
```

### Please provide the exception or error you saw

```true
Compiling rs-snowflake v0.6.0
error: failed to run custom build command for `zincobserve v0.1.0 (/home/marius/Media/Source/zincobserve)`

Caused by:
  process didn't exit successfully: `/home/marius/Media/Source/zincobserve/target/debug/build/zincobserve-25dfca9aa4c28be9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=proto
  cargo:rerun-if-changed=proto/cluster/common.proto
  cargo:rerun-if-changed=proto/cluster/event.proto
  cargo:rerun-if-changed=proto/cluster/metrics.proto
  cargo:rerun-if-changed=proto/cluster/search.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: cluster/metrics.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }', build.rs:58:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/panicking.rs:67:14
     2: core::result::unwrap_failed
               at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/result.rs:1651:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/result.rs:1076:23
     4: build_script_build::main
               at ./build.rs:23:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```
```


### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: master (Git)

marius@shell:~/Media/Source/zincobserve$ uname -mrs
Linux 5.15.0-71-generic x86_64
marius@shell:~/Media/Source/zincobserve$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

**Comment by hengfeiyang** [comment]
You should install protoc >=3.15

https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3

**Comment by hengfeiyang** [comment]
Maybe you can refer what we did: https://github.com/zinclabs/zincobserve/blob/main/.github/workflows/release.yml#LL88C35-L88C35

**Comment by norandom** [comment]
Wonderful, thank you for the help. The protoc compiler on Ubuntu 22.04 LTS was too old. Using the pre-compiled binaries resolved the issue: https://grpc.io/docs/protoc-installation/
